sudo: required
service :
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .
  
language: generic
deploy : 
    provide : elasticbeanstalk
    region : "us-east-2"
    app : "docker-react"
    env : "DockerReact-env"
    bucket_name : "elasticbeanstalk-us-east-2-964911151146"
    bucket_path : "docker-react"
    on : 
      branch : master
    access_key_id : $AWS_ACCESS_KEY
    secure_access_key : 
      secure : $AWS_SECRET_KEY
